## makeCacheMatrix takes a matrix as an argument and creates an object of type "list".
## This object of type "list" is designed to store: 
## a) an original matrix value
## b) a cached value of inversed matrix (initially set to NULL)

## makeCacheMatrix also defines 4 functions, they are not executed when makeCacheMatrix is called,
## they will be executed from cacheSolve 

makeCacheMatrix <- function(x = matrix()) {
## matrix created and its inverse object is set to NULL       
        m<-NULL

## set function takes a passed matrix, saves it and resets its inverse to NULL when new object is generated        
        set<-function(y){
                x<<-y
                m<<-NULL
        }
        
## get function returns the value of the original matrix when called from cacheSolve
        get<-function() {
                return(x)
        }
                
## setmatrix function designed to set and store the value of inverse matrix, called from cacheSolve
        setmatrix<-function(solve) {
                m<<- solve
        }
        
## getmatrix function returns the cached value of a matrix to cacheSolve with every subsequent access
        getmatrix<-function() {
                return(m)
        }        
        
## the object of type "list" is returned with all its properties (set,get,setmatrix,getmatrix)
        list(set=set, get=get,
             setmatrix=setmatrix,
             getmatrix=getmatrix) 

}


## cacheSolve function takes an object generated by makeCacheMatrix, 
## checks if there is a cached value stored from the previous attemts,
## if yes it returns cached data,
## if not it takes a passed matrix, computes its inverse, saves it and returns it
##
cacheSolve <- function(x, ...) {

## here we access object x (matrix) and get its cached value
        m<-x$getmatrix()

## if cached value is not null, then return cached value (in this case execution stops here)
        if(!is.null(m)){
            return(m)
        }

## if no cached value was found, then get the data
        my_data<-x$get()

## calculate inverse of the data (matrix)
        m<-solve(my_data, ...)

## store its value in m object
        x$setmatrix(m)

## return m object (inverse matrix)        
        m
}
