## makeCacheMatrix takes a matrix as an argument and creates an object of type "list".
## This object of type "list" designed to store: 
## a) an original matrix value
## b) a cached value of inversed matrix (initially set to NULL)

## There are 4 functions defined but not executed when makeCacheMatrix is called:
## 1) set - takes a passed matrix, saves it and resets inverse to NULL when new object is generated
## 2) get - this function returns the value of the original matrix when called from cacheSolve
## 3) setmatrix - designed to set and store the value of inverse matrix, called from cacheSolve
## 4) getmatrix - returns the cached value of a matrix to cacheSolve with every subsequent access

makeCacheMatrix <- function(x = matrix()) {
        
        m<-NULL
        
        set<-function(y){
                x<<-y
                m<<-NULL
        }
        
        get<-function() {
                return(x)
        }
                
        setmatrix<-function(solve) {
                m<<- solve
        }
        
        getmatrix<-function() {
                return(m)
        }        
        
        list(set=set, get=get,
             setmatrix=setmatrix,
             getmatrix=getmatrix) 

}

## cacheSolve takes an object generated by makeCacheMatrix, 
## checks if there is a cached value stored from the previous attemts,
## if yes it returns cached data,
## if not it takes a passed matrix, computes its inverse, saves it and returns it

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        
        m<-x$getmatrix()
        
        if(!is.null(m)){
                message("getting cached data")
                return(m)
        }
        
        my_data<-x$get()
        
        m<-solve(my_data, ...)
        
        x$setmatrix(m)
        
        m
}
